version: '2'
services:
  config-service:
    image: config-service
    ports:
     - "8080:8080"
  eureka-service:
    image: eureka-service
    depends_on:
     - config-service
    ports:
     - "8761:8761"
  user-service:
    image: user-service
    depends_on:
     - eureka-service
     - config-service
    ports:
     - "8000:8000"
