version: "2"
services:
  discovery:
    image: discovery-microservice
    ports:
      - "8761:8761"
  configserver:
    image: config-microservice
    ports:
      - "8888:8888"
    links:
      - discovery
  user:
    image: users-microservice
    ports:
      - "9000:9000"
    links:
      - discovery
      - configserver
