# All Spring admin, health ... endpoints are on the base url
# This property sets the url from which they should be called
# This allows easy security rules
management:
  context-path: /admin


server:
  port: 8000

spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true